title: Hello, I'm Nursoltan.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nursoltan Saipolda # add your name
author-img: profile.png # add your photo
about-author: Freelancer, full-time Topcoder competitor, project reviewer and gig worker. # add description
social-twitter: NursoltanS # add your Twitter handle
social-facebook: 100010840962859 # add your Facebook handle
social-github: nursoltan-s # add your Github handle
social-linkedin: nursoltan-saipolda-42b4b1195 # add your Linkedin handle
social-email: nursoltan.s@gmail.com # add your Email address

# Disqus
discus-identifier: nursoltan-com # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
